### ISSUE TITLE
[Templates] Support template with full names of fields for human readability

### ISSUE THREAD

**Issue by alsastre** [fernandezvara/certsfor#29]
Current template format is:
```
dn:
  cn: ""
  c: ""
  l: ""
  o: ""
  ou: ""
  p: ""
  pc: ""
  st: ""
san: []
key: rsa:4096
exp: 180
client: false
```

Support could be added for fullnames of fields. Ex:
```
domainName:
  commonName: ""
  country: ""
  location: ""
  organization: ""
  organizationalUnit: ""
...
```

Alternatively, information of each fields could be added in the documentation along with best-practices
